apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    app: app-monitor
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
  - port: nginx-exporter-port
    interval: 15s
