apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app-svc
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
  - port: 8002
    targetPort: 80
    protocol: TCP
    name: app-svc-port