kind: Service
apiVersion: v1
metadata:
  name: stress-test-service
  labels:
    apps: stress-test
spec:
  type: NodePort
  selector:
    app: stress-api
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30001
        protocol: TCP
        name: stress-test-port
    