apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: stress-api
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://stress-test-service:8000/metrics
      metricName: total_http_request
      threshold: '10'
      query: sum(rate(flask_http_request_total{method="GET",status="200"}[1m]))
